---
title: ""
listing:
  - id: data_science
    contents: "ds/*/index.qmd"
    type: default
    fields: [image, date, title, subtitle, categories, author, reading-time]  
    sort: "date desc"
    # categories: cloud
    sort-ui: true
    filter-ui: true
    page-size: 10
page-layout: full
toc: false
title-block-banner: false
include-in-header: ../meta.html
comments: false
---

<script>

document.addEventListener('DOMContentLoaded', function () {
    var categories = document.querySelectorAll('.listing-category');
    categories.forEach(function(category) {
        var textContent = category.textContent.trim();
        if (textContent === 'Intermediate') {
            category.classList.add('intermediate-category');
        } else if (textContent === 'Beginner') {
            category.classList.add('beginner-category');
        } else if (textContent === 'Advanced') {
            category.classList.add('advanced-category');
        }
    });
});

</script>



<style>
.beginner-category {
    /* Styles for "Beginner" */
    border-color: #4C8CBF !important; /* Sky Blue border */
    background-color: #7FB2E5; /* Light Blue background */
    color: #ffffff; /* White text */
    transition: background-color 0.3s ease; /* Smooth transition for hover effect */
}

.intermediate-category {
    /* Styles for "Intermediate" */
    background-color: #FFA500; /* Orange background */
    border-color: #FFA500 !important; /* Orange border */
    color: #ffffff; /* White text */
    transition: background-color 0.3s ease; /* Smooth transition for hover effect */
}

.advanced-category {
    /* Styles for "Advanced" */
    background-color: #6A0DAD; /* Purple background */
    border-color: #6A0DAD !important; /* Purple border */
    color: #ffffff; /* White text */
    transition: background-color 0.3s ease; /* Smooth transition for hover effect */
}

/* Optional: Add hover effects */
.beginner-category:hover {
    background-color: #4D9EDB; /* Brighter Blue on hover */
}

.intermediate-category:hover {
    background-color: #FF8C00; /* Darker Orange on hover */
}

.advanced-category:hover {
    background-color: #7D26CD; /* Darker Purple on hover */
}

</style>


# Teaching data science for non-data scientists

In today's data-informed world, tools of data science transcend industries, influencing decisions, shaping strategies, and transforming futures. Applications of data science also inform government decision-making and play a more central role than ever in people's lives. Yet, for many, the field remains shrouded in jargon and complexity. That's where we step in. Whether you're a professional looking to leverage data in your field, a student eager to expand your horizons, or simply a data enthusiast, our platform is designed with you in mind.

This website offers a fundamental exploration of data science tailored for non-data scientists, in particular ethicists and philosophers. The goal is to support a foundational understanding of the entire data science pipeline, from data collection and cleaning to analysis and the communication of findings.

A central focus of this project is the ethical reasoning within data science practices. By mastering the fundamental workflows, students will be equipped to critically assess and navigate the ethical dimensions of data usage and interpretation. The materials aim to empower students from diverse academic backgrounds to engage thoughtfully and responsibly with data, fostering a deeper appreciation of its impact across various domains.


## Data science case studies


::: {#data_science}
:::